### ISSUE TITLE
Error: name 'file' is not defined

### ISSUE THREAD

**Issue by MasterGroosha** [joefis/ansible-ipmi#1]
Hello! I'm trying to run IPMI command in ad-hoc mode which looks like this:
`ansible mynode -m ipmi -a 'credsfile="/root/ipmicreds.yml" name=mynode power=off'`

Contents of credsfile:
```
servers:
  - id: "mynode"
  - ilo-ip: "10.1.1.1"
  - ilo-user: "USER"
  - ilo-password: "PASSWORD"
```

However, I get the following error:
```
 [WARNING]: The value 5 (type int) in a string field was converted to '5' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

 [WARNING]: The value 12 (type int) in a string field was converted to '12' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.

mynode | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    }, 
    "changed": false, 
    "msg": "ipmi: name 'file' is not defined"
}
```

Could you please point me where is the error?
